sonar.projectKey=hireconnect-frontend
sonar.projectName=hireconnect-frontend
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.jsx,**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=src/setupTests.js,src/main.jsx,src/App.jsx,src/index.jsx,**/*.css,**/*.svg,**/*.png,src/api/**,src/pages/Dashboard.jsx,src/pages/Profile.jsx,src/pages/RecruiterDashboard.jsx,src/pages/JobDetail.jsx,src/pages/Jobs.jsx,src/pages/Login.jsx,src/pages/Register.jsx,src/pages/ForgotPassword.jsx,src/pages/Subscription.jsx,src/pages/RecruiterApply.jsx
sonar.host.url=http://localhost:9000
sonar.login=admin
sonar.password=Kundu@70677
sonar.sourceEncoding=UTF-8
